### ISSUE TITLE
{player} doesnt work

### ISSUE THREAD

**Issue by ItsMax123** [KygekTeam/KygekJoinUI#11]
the {player} doesnt work in the command on close

**Comment by Kygekraqmak** [comment]
Thanks for the issue!  
I've fixed this issue and you can wait for the new version to be released on Poggit. Or you can download it directly [here](https://poggit.pmmp.io/r/105509/KygekJoinUI_dev-47.phar).

Let me know if there are any further issues.
-- Kygekraqmak
